package com.git.stemming;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class StopWordsFileCreation {

	public static void createStopWordsFile() {
		
		
		try {
			FileWriter fileWriter = new FileWriter("stopwords.txt");
			BufferedWriter bw = new BufferedWriter(fileWriter);
			
			bw.write("a\r\n" + 
					"about\r\n" + 
					"above\r\n" + 
					"across\r\n" + 
					"after\r\n" + 
					"again\r\n" + 
					"against\r\n" + 
					"all\r\n" + 
					"almost\r\n" + 
					"alone\r\n" + 
					"along\r\n" + 
					"already\r\n" + 
					"also\r\n" + 
					"although\r\n" + 
					"always\r\n" + 
					"among\r\n" + 
					"an\r\n" + 
					"and\r\n" + 
					"another\r\n" + 
					"any\r\n" + 
					"anybody\r\n" + 
					"anyone\r\n" + 
					"anything\r\n" + 
					"anywhere\r\n" + 
					"are\r\n" + 
					"area\r\n" + 
					"areas\r\n" + 
					"around\r\n" + 
					"as\r\n" + 
					"ask\r\n" + 
					"asked\r\n" + 
					"asking\r\n" + 
					"asks\r\n" + 
					"at\r\n" + 
					"away\r\n" + 
					"b\r\n" + 
					"back\r\n" + 
					"backed\r\n" + 
					"backing\r\n" + 
					"backs\r\n" + 
					"be\r\n" + 
					"became\r\n" + 
					"because\r\n" + 
					"become\r\n" + 
					"becomes\r\n" + 
					"been\r\n" + 
					"before\r\n" + 
					"began\r\n" + 
					"behind\r\n" + 
					"being\r\n" + 
					"beings\r\n" + 
					"best\r\n" + 
					"better\r\n" + 
					"between\r\n" + 
					"big\r\n" + 
					"both\r\n" + 
					"but\r\n" + 
					"by\r\n" + 
					"c\r\n" + 
					"came\r\n" + 
					"can\r\n" + 
					"cannot\r\n" + 
					"case\r\n" + 
					"cases\r\n" + 
					"certain\r\n" + 
					"certainly\r\n" + 
					"clear\r\n" + 
					"clearly\r\n" + 
					"come\r\n" + 
					"could\r\n" + 
					"d\r\n" + 
					"did\r\n" + 
					"differ\r\n" + 
					"different\r\n" + 
					"differently\r\n" + 
					"do\r\n" + 
					"does\r\n" + 
					"done\r\n" + 
					"down\r\n" + 
					"down\r\n" + 
					"downed\r\n" + 
					"downing\r\n" + 
					"downs\r\n" + 
					"during\r\n" + 
					"e\r\n" + 
					"each\r\n" + 
					"early\r\n" + 
					"either\r\n" + 
					"end\r\n" + 
					"ended\r\n" + 
					"ending\r\n" + 
					"ends\r\n" + 
					"enough\r\n" + 
					"even\r\n" + 
					"evenly\r\n" + 
					"ever\r\n" + 
					"every\r\n" + 
					"everybody\r\n" + 
					"everyone\r\n" + 
					"everything\r\n" + 
					"everywhere\r\n" + 
					"f\r\n" + 
					"face\r\n" + 
					"faces\r\n" + 
					"fact\r\n" + 
					"facts\r\n" + 
					"far\r\n" + 
					"felt\r\n" + 
					"few\r\n" + 
					"find\r\n" + 
					"finds\r\n" + 
					"first\r\n" + 
					"for\r\n" + 
					"four\r\n" + 
					"from\r\n" + 
					"full\r\n" + 
					"fully\r\n" + 
					"further\r\n" + 
					"furthered\r\n" + 
					"furthering\r\n" + 
					"furthers\r\n" + 
					"g\r\n" + 
					"gave\r\n" + 
					"general\r\n" + 
					"generally\r\n" + 
					"get\r\n" + 
					"gets\r\n" + 
					"give\r\n" + 
					"given\r\n" + 
					"gives\r\n" + 
					"go\r\n" + 
					"going\r\n" + 
					"good\r\n" + 
					"goods\r\n" + 
					"got\r\n" + 
					"great\r\n" + 
					"greater\r\n" + 
					"greatest\r\n" + 
					"group\r\n" + 
					"grouped\r\n" + 
					"grouping\r\n" + 
					"groups\r\n" + 
					"h\r\n" + 
					"had\r\n" + 
					"has\r\n" + 
					"have\r\n" + 
					"having\r\n" + 
					"he\r\n" + 
					"her\r\n" + 
					"here\r\n" + 
					"herself\r\n" + 
					"high\r\n" + 
					"high\r\n" + 
					"high\r\n" + 
					"higher\r\n" + 
					"highest\r\n" + 
					"him\r\n" + 
					"himself\r\n" + 
					"his\r\n" + 
					"how\r\n" + 
					"however\r\n" + 
					"i\r\n" + 
					"if\r\n" + 
					"important\r\n" + 
					"in\r\n" + 
					"interest\r\n" + 
					"interested\r\n" + 
					"interesting\r\n" + 
					"interests\r\n" + 
					"into\r\n" + 
					"is\r\n" + 
					"it\r\n" + 
					"its\r\n" + 
					"itself\r\n" + 
					"j\r\n" + 
					"just\r\n" + 
					"k\r\n" + 
					"keep\r\n" + 
					"keeps\r\n" + 
					"kind\r\n" + 
					"knew\r\n" + 
					"know\r\n" + 
					"known\r\n" + 
					"knows\r\n" + 
					"l\r\n" + 
					"large\r\n" + 
					"largely\r\n" + 
					"last\r\n" + 
					"later\r\n" + 
					"latest\r\n" + 
					"least\r\n" + 
					"less\r\n" + 
					"let\r\n" + 
					"lets\r\n" + 
					"like\r\n" + 
					"likely\r\n" + 
					"long\r\n" + 
					"longer\r\n" + 
					"longest\r\n" + 
					"m\r\n" + 
					"made\r\n" + 
					"make\r\n" + 
					"making\r\n" + 
					"man\r\n" + 
					"many\r\n" + 
					"may\r\n" + 
					"me\r\n" + 
					"member\r\n" + 
					"members\r\n" + 
					"men\r\n" + 
					"might\r\n" + 
					"more\r\n" + 
					"most\r\n" + 
					"mostly\r\n" + 
					"mr\r\n" + 
					"mrs\r\n" + 
					"much\r\n" + 
					"must\r\n" + 
					"my\r\n" + 
					"myself\r\n" + 
					"n\r\n" + 
					"necessary\r\n" + 
					"need\r\n" + 
					"needed\r\n" + 
					"needing\r\n" + 
					"needs\r\n" + 
					"never\r\n" + 
					"new\r\n" + 
					"new\r\n" + 
					"newer\r\n" + 
					"newest\r\n" + 
					"next\r\n" + 
					"no\r\n" + 
					"nobody\r\n" + 
					"non\r\n" + 
					"noone\r\n" + 
					"not\r\n" + 
					"nothing\r\n" + 
					"now\r\n" + 
					"nowhere\r\n" + 
					"number\r\n" + 
					"numbers\r\n" + 
					"o\r\n" + 
					"of\r\n" + 
					"off\r\n" + 
					"often\r\n" + 
					"old\r\n" + 
					"older\r\n" + 
					"oldest\r\n" + 
					"on\r\n" + 
					"once\r\n" + 
					"one\r\n" + 
					"only\r\n" + 
					"open\r\n" + 
					"opened\r\n" + 
					"opening\r\n" + 
					"opens\r\n" + 
					"or\r\n" + 
					"order\r\n" + 
					"ordered\r\n" + 
					"ordering\r\n" + 
					"orders\r\n" + 
					"other\r\n" + 
					"others\r\n" + 
					"our\r\n" + 
					"out\r\n" + 
					"over\r\n" + 
					"p\r\n" + 
					"part\r\n" + 
					"parted\r\n" + 
					"parting\r\n" + 
					"parts\r\n" + 
					"per\r\n" + 
					"perhaps\r\n" + 
					"place\r\n" + 
					"places\r\n" + 
					"point\r\n" + 
					"pointed\r\n" + 
					"pointing\r\n" + 
					"points\r\n" + 
					"possible\r\n" + 
					"present\r\n" + 
					"presented\r\n" + 
					"presenting\r\n" + 
					"presents\r\n" + 
					"problem\r\n" + 
					"problems\r\n" + 
					"put\r\n" + 
					"puts\r\n" + 
					"q\r\n" + 
					"quite\r\n" + 
					"r\r\n" + 
					"rather\r\n" + 
					"really\r\n" + 
					"right\r\n" + 
					"right\r\n" + 
					"room\r\n" + 
					"rooms\r\n" + 
					"s\r\n" + 
					"said\r\n" + 
					"same\r\n" + 
					"saw\r\n" + 
					"say\r\n" + 
					"says\r\n" + 
					"second\r\n" + 
					"seconds\r\n" + 
					"see\r\n" + 
					"seem\r\n" + 
					"seemed\r\n" + 
					"seeming\r\n" + 
					"seems\r\n" + 
					"sees\r\n" + 
					"several\r\n" + 
					"shall\r\n" + 
					"she\r\n" + 
					"should\r\n" + 
					"show\r\n" + 
					"showed\r\n" + 
					"showing\r\n" + 
					"shows\r\n" + 
					"side\r\n" + 
					"sides\r\n" + 
					"since\r\n" + 
					"small\r\n" + 
					"smaller\r\n" + 
					"smallest\r\n" + 
					"so\r\n" + 
					"some\r\n" + 
					"somebody\r\n" + 
					"someone\r\n" + 
					"something\r\n" + 
					"somewhere\r\n" + 
					"state\r\n" + 
					"states\r\n" + 
					"still\r\n" + 
					"still\r\n" + 
					"such\r\n" + 
					"sure\r\n" + 
					"t\r\n" + 
					"take\r\n" + 
					"taken\r\n" + 
					"than\r\n" + 
					"that\r\n" + 
					"the\r\n" + 
					"their\r\n" + 
					"them\r\n" + 
					"then\r\n" + 
					"there\r\n" + 
					"therefore\r\n" + 
					"these\r\n" + 
					"they\r\n" + 
					"thing\r\n" + 
					"things\r\n" + 
					"think\r\n" + 
					"thinks\r\n" + 
					"this\r\n" + 
					"those\r\n" + 
					"though\r\n" + 
					"thought\r\n" + 
					"thoughts\r\n" + 
					"three\r\n" + 
					"through\r\n" + 
					"thus\r\n" + 
					"to\r\n" + 
					"today\r\n" + 
					"together\r\n" + 
					"too\r\n" + 
					"took\r\n" + 
					"toward\r\n" + 
					"turn\r\n" + 
					"turned\r\n" + 
					"turning\r\n" + 
					"turns\r\n" + 
					"two\r\n" + 
					"u\r\n" + 
					"under\r\n" + 
					"until\r\n" + 
					"up\r\n" + 
					"upon\r\n" + 
					"us\r\n" + 
					"use\r\n" + 
					"used\r\n" + 
					"uses\r\n" + 
					"v\r\n" + 
					"very\r\n" + 
					"w\r\n" + 
					"want\r\n" + 
					"wanted\r\n" + 
					"wanting\r\n" + 
					"wants\r\n" + 
					"was\r\n" + 
					"way\r\n" + 
					"ways\r\n" + 
					"we\r\n" + 
					"well\r\n" + 
					"wells\r\n" + 
					"went\r\n" + 
					"were\r\n" + 
					"what\r\n" + 
					"when\r\n" + 
					"where\r\n" + 
					"whether\r\n" + 
					"which\r\n" + 
					"while\r\n" + 
					"who\r\n" + 
					"whole\r\n" + 
					"whose\r\n" + 
					"why\r\n" + 
					"will\r\n" + 
					"with\r\n" + 
					"within\r\n" + 
					"without\r\n" + 
					"work\r\n" + 
					"worked\r\n" + 
					"working\r\n" + 
					"works\r\n" + 
					"would\r\n" + 
					"x\r\n" + 
					"y\r\n" + 
					"year\r\n" + 
					"years\r\n" + 
					"yet\r\n" + 
					"you\r\n" + 
					"young\r\n" + 
					"younger\r\n" + 
					"youngest\r\n" + 
					"your\r\n" + 
					"yours\r\n" + 
					"z");
			
			bw.close();
			fileWriter.close();
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		
		
	}
}
